<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        <img src ="logo/Pets.jpg" width="40" height="40" alt="Logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
              <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="index.php#dogs">Dogs</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="index.php#cats">Cats</a>
          </li>
      </ul>
    </div>
    <div class="right">
        <ul class=<"navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <!-- Instead of using href="#register" use href"=register.php" -->
              <!-- '#' is for current page-->
              <a class="nav-link" href="register.php"><i class="fa fa-user-circle" style="font-size:24px"></i></a>
          </li>
          <li class="nav-item">
              <!-- Instead of using href="#login" use href"=login.php" -->
              <!-- '#' is for current page-->
              <a class="nav-link" href="login.php"><i class="fa fa-sign-in" style="font-size:24px"></i></a>
          </li>
        </ul>
    </div>
</nav>